In [1]:
from nba_api.stats.endpoints import LeagueGameLog
import pandas as pd
import numpy as np
from get_lineups import get_lineups
from label_play_by_play import get_labelled_play_by_play

In [2]:

seasons = ['2024-25']

# Get game_ids
for season in seasons:
    game_log = LeagueGameLog(season=season).get_data_frames()[0]

df = pd.DataFrame(game_log)
game_ids = df['GAME_ID'].unique()

In [3]:
print(game_ids[0])

0022400061

In [4]:
for game_id in game_ids[:1]:
    lineup = get_lineups(game_id)
    pbp = get_labelled_play_by_play(game_id)

c:\Code\NBA-Adjusted-Plus-Minus\get_lineups.py:55: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  lineup = pd.concat(

In [6]:
pbp

,actionNumber,teamId,scoreHome,scoreAway,description,actionType,subType,time,location,newPossession,possession,possessionCount
0,2,0,0,0,Start of 1st Period (7:36 PM EST),period,start,0.0,,False,None,0
1,4,1610612738,0,0,Jump Ball Horford vs. Towns: Tip to White,Jump Ball,,0.0,h,True,BOS,1
2,7,1610612738,3,0,Tatum 27' 3PT Pullup Jump Shot (3 PTS) (White ...,Made Shot,Pullup Jump shot,120.0,h,False,BOS,1
3,9,1610612752,3,2,Anunoby 6' Driving Layup (2 PTS) (Brunson 1 AST),Made Shot,Driving Layup Shot,330.0,v,True,NYK,2
4,11,1610612738,3,2,MISS Tatum 26' 3PT Pullup Jump Shot,Missed Shot,Pullup Jump shot,440.0,h,True,BOS,3
...,...,...,...,...,...,...,...,...,...,...,...,...
397,544,0,132,109,Knicks Rebound,Rebound,Unknown,28289.0,v,True,NYK,180
398,546,1610612752,132,109,MISS Toppin 25' 3PT Jump Shot,Missed Shot,Jump Shot,28431.0,v,False,NYK,180
399,547,0,132,109,CELTICS Rebound,Rebound,Unknown,28444.0,h,True,BOS,181
400,549,0,132,109,CELTICS Turnover: Shot Clock (T#4),Turnover,Shot Clock Turnover,28690.0,h,False,BOS,181
401,550,0,132,109,End of 4th Period (9:40 PM EST),period,end,28800.0,,True,NYK,182