# Get game ids

In [2]:
from nba_api.stats.endpoints import LeagueGameLog
import pandas as pd
import numpy as np

In [13]:
help(LeagueGameLog)

Help on class LeagueGameLog in module nba_api.stats.endpoints.leaguegamelog:

class LeagueGameLog(nba_api.stats.endpoints._base.Endpoint)
 |  LeagueGameLog(counter=0, direction='ASC', league_id='00', player_or_team_abbreviation='T', season='2024-25', season_type_all_star='Regular Season', sorter='DATE', date_from_nullable='', date_to_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
 |
 |  Method resolution order:
 |      LeagueGameLog
 |      nba_api.stats.endpoints._base.Endpoint
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, counter=0, direction='ASC', league_id='00', player_or_team_abbreviation='T', season='2024-25', season_type_all_star='Regular Season', sorter='DATE', date_from_nullable='', date_to_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  get_request(self)
 |
 |  load_response(self)
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  data_sets = None
 |
 |  endpoint = 'leaguegamelog'
 |
 |  expected_data = {'LeagueGameLog': ['SEASON_ID', 'TEAM_ID', 'TEAM_ABBRE...
 |
 |  headers = None
 |
 |  nba_response = None
 |
 |  player_stats = None
 |
 |  team_stats = None
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from nba_api.stats.endpoints._base.Endpoint:
 |
 |  get_available_data(self)
 |
 |  get_data_frames(self)
 |
 |  get_dict(self)
 |
 |  get_json(self)
 |
 |  get_normalized_dict(self)
 |
 |  get_normalized_json(self)
 |
 |  get_request_url(self)
 |
 |  get_response(self)
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from nba_api.stats.endpoints._base.Endpoint:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from nba_api.stats.endpoints._base.Endpoint:
 |
 |  DataSet = <class 'nba_api.stats.endpoints._base.Endpoint.DataSet'>

In [14]:
help(LeagueGameLog.get_request)

Help on function get_request in module nba_api.stats.endpoints.leaguegamelog:

get_request(self)

In [22]:
np.squeeze?

Signature:       np.squeeze(a, axis=None)
Call signature:  np.squeeze(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function squeeze at 0x000001F6D6E4C680>
File:            c:\code\nba-adjusted-plus-minus\venv\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:
Remove axes of length one from `a`.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Selects a subset of the entries of length one in the
    shape. If an axis is selected with shape entry greater than
    one, an error is raised.

Returns
-------
squeezed : ndarray
    The input array, but with all or a subset of the
    dimensions of length 1 removed. This is always `a` itself
    or a view into `a`. Note that if all axes are squeezed,
    the result is a 0d array and not a scalar.

Raises
------
ValueError
    If `axis` is not None, and an axis being squeezed is not of length 1

See Also
--------
expand_dims : The inverse operation, adding entries of length one
reshape : Insert, remove, and combine dimensions, and resize existing ones

Examples
--------
>>> import numpy as np
>>> x = np.array([[[0], [1], [2]]])
>>> x.shape
(1, 3, 1)
>>> np.squeeze(x).shape
(3,)
>>> np.squeeze(x, axis=0).shape
(3, 1)
>>> np.squeeze(x, axis=1).shape
Traceback (most recent call last):
...
ValueError: cannot select an axis to squeeze out which has size
not equal to one
>>> np.squeeze(x, axis=2).shape
(1, 3)
>>> x = np.array([[1234]])
>>> x.shape
(1, 1)
>>> np.squeeze(x)
array(1234)  # 0d array
>>> np.squeeze(x).shape
()
>>> np.squeeze(x)[()]
1234
Class docstring:
Class to wrap functions with checks for __array_function__ overrides.

All arguments are required, and can only be passed by position.

Parameters
----------
dispatcher : function or None
    The dispatcher function that returns a single sequence-like object
    of all arguments relevant.  It must have the same signature (except
    the default values) as the actual implementation.
    If ``None``, this is a ``like=`` dispatcher and the
    ``_ArrayFunctionDispatcher`` must be called with ``like`` as the
    first (additional and positional) argument.
implementation : function
    Function that implements the operation on NumPy arrays without
    overrides.  Arguments passed calling the ``_ArrayFunctionDispatcher``
    will be forwarded to this (and the ``dispatcher``) as if using
    ``*args, **kwargs``.

Attributes
----------
_implementation : function
    The original implementation passed in.

In [3]:
game_log = LeagueGameLog().get_data_frames()

In [4]:
pd.DataFrame(np.squeeze(game_log)).head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,22024,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,240,43,...,29,34,20,2,3,12,12,109,-23,1
1,22024,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,240,48,...,29,40,33,6,3,4,15,132,23,1
2,22024,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,240,42,...,31,46,22,7,8,7,22,110,7,1
3,22024,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,240,35,...,35,47,17,4,1,16,22,103,-7,1
4,22024,1610612766,CHA,Charlotte Hornets,0022400068,2024-10-23,CHA @ HOU,W,240,38,...,41,56,20,6,10,17,21,110,5,1

In [11]:
print(game_log)

<nba_api.stats.endpoints.leaguegamelog.LeagueGameLog object at 0x000002B20A8A00D0>

# Get play by play for game

In [ ]:
from nba_api.stats.endpoints import PlayByPlay

In [13]:
play = PlayByPlay(game_id= '0000000001', start_period= '1', end_period= '1')
response = play.get_data_frames()
print(response)

[Empty DataFrame
Columns: [GAME_ID, EVENTNUM, EVENTMSGTYPE, EVENTMSGACTIONTYPE, PERIOD, WCTIMESTRING, PCTIMESTRING, HOMEDESCRIPTION, NEUTRALDESCRIPTION, VISITORDESCRIPTION, SCORE, SCOREMARGIN]
Index: [], Empty DataFrame
Columns: [VIDEO_AVAILABLE_FLAG]
Index: []]

None